### PR TITLE
Fix re-rendering when prompt is exactly the width of the terminal

### LINKED ISSUE #318: Typing into prompt clears previous lines in terminal
**What operating system and terminal are you using?**
MacOS Catalina / iTerm. Saw this on MacOS High Sierra as well.

**An example that showcases the bug.**
I've attached a video of the bug in this zip file: [BugDemo.zip](https://github.com/AlecAivazis/survey/files/5619166/BugDemo.zip)

It seems that when I adjust the width of my terminal tab so that the prompt text is all the way at the end of the terminal screen (i.e. no whitespace between the last character in the prompt description text - ":" in this case -  and the end of the terminal screen), a line in my terminal is cleared every time I type a character.

**What did you expect to see?**
I would expect my terminal to remain as is when I type input into a prompt.

**What did you see instead?**
I saw my terminal clear when I typed given the specifications above.

### PR DESCRIPTION
**Pull request by mislav**
The code that measures width of rendered lines of content and whether any have overflown in the terminal did not account for the possibility that the content could be _exactly_ the width of the terminal. In that case, it shouldn't be counted as overflow.

Fixes #318
Followup to #291, #288

### CODE REVIEW

File: renderer_posix_test.go [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+	"github.com/stretchr/testify/require"
+)
+
+func TestRenderer_countLines(t *testing.T) {
+	t.Parallel()
+
+	termWidth := 72
+	stdout := new(bytes.Buffer)
+	c, _, err := vt10x.NewVT10XConsole(expect.WithStdout(stdout))
+	vt10x.ResizePty(c.Tty(), termWidth, 30)
```
Comment (mislav) [inline renderer_posix_test.go:22]: This test is marked as POSIX-only because it allocates a pseudo-terminal to emulate a scenario when the terminal is of a specific width. If anyone knows of a more lightweight approach to generate a terminal at a file descriptor that pretends to be a certain size, I'm all ears!

**Comment by AlecAivazis** [comment]
Thanks for fixing this @mislav - i verified the behavior on both apple and windows.

Thanks for being patient while we wrangle this! Maintaining this project alone takes a lot of time and attention, two things i haven't had much of in the past month.

**Comment by AlecAivazis** [comment]
On that note, are there any extra resources at GitHub that can help me test PRs and releases? There have been two regressions in the past month that are mostly due to me juggling multiple things at once, i would like to find a way to make sure that doesn't happen again

**Comment by mislav** [comment]
@AlecAivazis Sure, let us know how we can help. We are just 3 devs and don't have infinite resources either, but we rely quite a lot on Survey and we'd like to have it be stable. A lot of problems that our users reported with GitHub CLI were fixed over the last few releases of Survey, and we appreciate that!

We are also wondering whether you would be open to contributions that improve accessibility by positioning the cursor at the right place, and possibly allowing custom keybindings to Prompt components like the Editor.

**Comment by mislav** [comment]
BTW, thank you for making a patch release in such a short time! 🙇 ❤️
